import { NgModule } from '@angular/core';

import {MatInputModule,
  MatIconModule,
  MatTreeModule,
  MatSelectModule,
  MatExpansionModule,
  MatDatepickerModule,
  MatButtonModule,
  MatCheckboxModule,
  MatRadioModule,
  MatFormFieldModule,
  MatNativeDateModule,
  MatSortModule,
  MatAutocompleteModule,
  MatSlideToggleModule,
  MatBadgeModule,
  MatPaginatorModule,
  MatTableModule,
  MatStepperModule,
  MatTabsModule,
  MatCardModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatDividerModule
  } from '@angular/material';

@NgModule({
  imports: [
    MatExpansionModule,
    MatTreeModule,
    MatIconModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
    MatButtonModule,
    MatCheckboxModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSortModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatBadgeModule,
    MatTableModule,
    MatPaginatorModule,
    MatStepperModule,
    MatTabsModule,
    MatCardModule,
    MatInputModule,
    MatButtonModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatDividerModule
  ],
  exports: [
    MatExpansionModule,
    MatTreeModule,
    MatIconModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
    MatButtonModule,
    MatCheckboxModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSortModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatBadgeModule,
    MatPaginatorModule,
    MatCardModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatCardModule,
    MatInputModule,
    MatButtonModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatDividerModule
  ]
})

export class MaterialModule {

}
